//! GOLD-FEAT-03b — capability-map wiki pages.
//!
//! Renders [`crate::memory::self_wiki`] (the compile-time map of every
//! skill / cron / CLI / slash command the binary ships) into Obsidian
//! pages. This IS the "corpus ships in-binary" half of the self-wiki:
//! unlike the `PLAN/` design docs (dev checkouts only), these pages are
//! generated from `&'static` tables and therefore exist — and stay
//! current — in every release build. Pure (no I/O); the cron writes the
//! returned pages.

use crate::memory::self_wiki::{self, CapabilityEntry, CapabilityKind};

/// Index page file name (with `.md`).
pub const CAPABILITIES_INDEX_FILE: &str = "NEOTH Capabilities.md";

const KINDS: [(CapabilityKind, &str, &str); 4] = [
    (
        CapabilityKind::Skill,
        "NEOTH Capabilities - Skills.md",
        "Bundled skills",
    ),
    (
        CapabilityKind::Cron,
        "NEOTH Capabilities - Crons.md",
        "Daemon crons",
    ),
    (
        CapabilityKind::CliCommand,
        "NEOTH Capabilities - CLI Commands.md",
        "CLI commands",
    ),
    (
        CapabilityKind::SlashCommand,
        "NEOTH Capabilities - Slash Commands.md",
        "Slash commands",
    ),
];

fn render_kind_page(title: &str, entries: &[&CapabilityEntry]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# {title}\n\nGenerated from the in-binary capability map \
         (`memory::self_wiki`) — always matches the running build.\n\n\
         | id | description | gate |\n|---|---|---|\n"
    ));
    for e in entries {
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            e.id,
            e.description.replace('|', "\\|"),
            e.feature_gate.unwrap_or("—"),
        ));
    }
    out.push('\n');
    out
}

/// Render the capability index + one page per capability kind.
/// Returns `(file_name, markdown)` pairs; file names are fixed so the
/// rebuild cron is idempotent (plain overwrite).
pub fn render_capability_pages() -> Vec<(String, String)> {
    let wiki = self_wiki::build();
    let mut pages = Vec::with_capacity(KINDS.len() + 1);

    let mut index = String::from(
        "# NEOTH Capabilities\n\nLive self-map of everything this binary \
         ships. Regenerated by the self-wiki cron (`self_wiki.enabled`).\n\n",
    );
    index.push_str(&format!("```\n{}\n```\n\n", wiki.summary()));
    for (_, file, heading) in KINDS.iter() {
        let link = file.trim_end_matches(".md");
        index.push_str(&format!("- [[{link}]] — {heading}\n"));
    }
    pages.push((CAPABILITIES_INDEX_FILE.to_string(), index));

    for (kind, file, heading) in KINDS.iter() {
        let entries: Vec<&CapabilityEntry> =
            wiki.all().filter(|e| e.kind == *kind).collect();
        pages.push(((*file).to_string(), render_kind_page(heading, &entries)));
    }
    pages
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_index_plus_one_page_per_kind() {
        let pages = render_capability_pages();
        assert_eq!(pages.len(), 5, "index + 4 kind pages");
        assert_eq!(pages[0].0, CAPABILITIES_INDEX_FILE);
        // Every page is non-trivial markdown with a heading.
        for (name, body) in &pages {
            assert!(name.ends_with(".md"), "{name} must be a .md file");
            assert!(body.starts_with("# "), "{name} must start with a heading");
            assert!(body.len() > 100, "{name} suspiciously empty");
        }
        // The skills page contains a known bundled skill id.
        let skills = &pages[1].1;
        assert!(
            skills.contains("`anti_slop`"),
            "skills page lists bundled skills"
        );
    }

    #[test]
    fn index_links_every_kind_page() {
        let pages = render_capability_pages();
        let index = &pages[0].1;
        for (name, _) in pages.iter().skip(1) {
            let link = name.trim_end_matches(".md");
            assert!(
                index.contains(&format!("[[{link}]]")),
                "index must wikilink {link}"
            );
        }
    }
}
