//! GOLD-FEAT-03 — self-wiki page rendering.
//!
//! Pure markdown layout for the Obsidian self-wiki: one [`render_page`] per
//! source (frontmatter + H1 + `[[wikilink]]` cross-refs to same-category
//! siblings + a bounded body excerpt) plus a [`render_index`] Map-of-Content.
//! No I/O — bodies are passed in by the writer — so layout is unit-tested
//! deterministically.

use crate::wiki::sources::{SourceCategory, WikiSource};

/// Max bytes of source body embedded in a page. The full doc stays in the repo;
/// a wiki page is a navigable summary + link, not a copy.
pub const EXCERPT_BYTES: usize = 1200;

/// All categories in index/display order.
pub const CATEGORY_ORDER: [SourceCategory; 4] = [
    SourceCategory::Design,
    SourceCategory::Spec,
    SourceCategory::Chorus,
    SourceCategory::Other,
];

/// Escape a string for use inside a double-quoted YAML scalar.
fn yaml_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Truncate `body` to at most `max_bytes`, never splitting a UTF-8 char.
fn excerpt_of(body: &str, max_bytes: usize) -> &str {
    if body.len() <= max_bytes {
        return body;
    }
    let mut end = max_bytes;
    while end > 0 && !body.is_char_boundary(end) {
        end -= 1;
    }
    &body[..end]
}

/// Render one source into an Obsidian markdown page. `siblings` is the set of
/// pages this one cross-links to (typically same-category); `body` is the raw
/// source text (the writer reads the file once and passes it here).
pub fn render_page(source: &WikiSource, siblings: &[&WikiSource], body: &str) -> String {
    let mut s = String::new();
    s.push_str("---\n");
    s.push_str(&format!("title: \"{}\"\n", yaml_escape(&source.title)));
    s.push_str(&format!("category: {}\n", source.category.tag()));
    s.push_str(&format!("tags: [neoth-wiki, {}]\n", source.category.tag()));
    s.push_str(&format!("source: \"{}\"\n", yaml_escape(&source.rel_path)));
    s.push_str("---\n\n");

    s.push_str(&format!("# {}\n\n", source.title));
    s.push_str(&format!(
        "> NEOTH self-wiki page (GOLD-FEAT-03). The authoritative doc is `{}`.\n\n",
        source.rel_path
    ));

    let related: Vec<&WikiSource> = siblings
        .iter()
        .copied()
        .filter(|x| x.slug != source.slug)
        .collect();
    if !related.is_empty() {
        s.push_str("## Related\n\n");
        for r in &related {
            s.push_str(&format!("- [[{}]]\n", r.slug));
        }
        s.push('\n');
    }

    s.push_str("## Excerpt\n\n");
    let excerpt = excerpt_of(body, EXCERPT_BYTES);
    s.push_str(excerpt);
    if excerpt.len() < body.len() {
        s.push_str("\n\n*(truncated — see the source doc for the full text)*\n");
    } else {
        s.push('\n');
    }
    s
}

/// The basename of the index page (the wiki's entry point).
pub const INDEX_SLUG: &str = "NEOTH-Wiki-Index";

/// Render the Map-of-Content index linking every source, grouped by category.
pub fn render_index(sources: &[WikiSource]) -> String {
    let mut s = String::new();
    s.push_str("---\n");
    s.push_str("title: \"NEOTH Self-Wiki\"\n");
    s.push_str("tags: [neoth-wiki, index]\n");
    s.push_str("---\n\n");
    s.push_str("# NEOTH Self-Wiki\n\n");
    s.push_str(&format!(
        "> Generated by `neoth obsidian wiki-build` (GOLD-FEAT-03) from {} design docs.\n\n",
        sources.len()
    ));

    for cat in CATEGORY_ORDER {
        let in_cat: Vec<&WikiSource> = sources.iter().filter(|x| x.category == cat).collect();
        if in_cat.is_empty() {
            continue;
        }
        s.push_str(&format!("## {}\n\n", cat.heading()));
        for src in in_cat {
            s.push_str(&format!("- [[{}]] — {}\n", src.slug, src.title));
        }
        s.push('\n');
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn src(slug: &str, title: &str, cat: SourceCategory) -> WikiSource {
        WikiSource {
            title: title.to_string(),
            slug: slug.to_string(),
            rel_path: format!("{slug}.md"),
            abs_path: PathBuf::from(format!("/x/{slug}.md")),
            category: cat,
        }
    }

    #[test]
    fn page_has_frontmatter_title_related_and_excerpt() {
        let a = src("SPEC_a", "Spec A", SourceCategory::Spec);
        let b = src("SPEC_b", "Spec B", SourceCategory::Spec);
        let page = render_page(&a, &[&a, &b], "the body text");
        assert!(page.starts_with("---\n"));
        assert!(page.contains("title: \"Spec A\""));
        assert!(page.contains("tags: [neoth-wiki, spec]"));
        assert!(page.contains("source: \"SPEC_a.md\""));
        assert!(page.contains("# Spec A"));
        // self is filtered out of Related; sibling linked.
        assert!(page.contains("- [[SPEC_b]]"));
        assert!(!page.contains("- [[SPEC_a]]"));
        assert!(page.contains("## Excerpt"));
        assert!(page.contains("the body text"));
    }

    #[test]
    fn page_without_siblings_omits_related_block() {
        let a = src("SPEC_a", "Spec A", SourceCategory::Spec);
        let page = render_page(&a, &[&a], "body");
        assert!(!page.contains("## Related"));
    }

    #[test]
    fn excerpt_truncates_on_char_boundary_and_marks_it() {
        // Multi-byte chars right at the boundary must not panic / split.
        let body = "é".repeat(2000); // 4000 bytes
        let a = src("x", "X", SourceCategory::Other);
        let page = render_page(&a, &[], &body);
        assert!(page.contains("*(truncated"));
        // The embedded excerpt is valid UTF-8 (no panic on the boundary walk).
        assert!(page.contains('é'));
    }

    #[test]
    fn yaml_escape_handles_quotes_and_backslashes() {
        let a = src("x", r#"Title with "quotes" and \ slash"#, SourceCategory::Other);
        let page = render_page(&a, &[], "b");
        assert!(page.contains(r#"title: "Title with \"quotes\" and \\ slash""#));
    }

    #[test]
    fn index_groups_by_category_in_order() {
        let sources = vec![
            src("CHORUS_x", "Chorus X", SourceCategory::Chorus),
            src("00_DESIGN", "Design", SourceCategory::Design),
            src("SPEC_a", "Spec A", SourceCategory::Spec),
        ];
        let idx = render_index(&sources);
        let design_pos = idx.find("## Design").unwrap();
        let spec_pos = idx.find("## Specifications").unwrap();
        let chorus_pos = idx.find("## Chorus Verdicts").unwrap();
        assert!(design_pos < spec_pos && spec_pos < chorus_pos, "category order");
        assert!(idx.contains("- [[SPEC_a]] — Spec A"));
        assert!(idx.contains("from 3 design docs"));
    }
}
