//! GOLD-ADAPT-OH-01 — prior-AI source detector.
//!
//! Scans the complete install homes of the assistants NEOTH knows how to
//! import (OpenClaw, Hermes, OpenHuman, Veronica) and generates a
//! ready-to-edit `import-manifest.yaml` for `dry-run` / `apply`. Nothing
//! is imported here — detection is read-only and the operator reviews
//! the generated manifest before running `apply --confirm`.
//!
//! A generated `assistant_home` source recursively discovers every supported
//! memory artifact below that home. Custom roots remain operator-declarable.

use std::path::{Path, PathBuf};

use crate::readers::{ImportKind, ImportManifest, ImportSource, StoreScan, scan_all};

/// One prior-assistant home candidate: (relative-to-operator-home path,
/// source name, family hint). Legacy OpenClaw names and OpenHuman's staging
/// home are explicit so upgrades do not strand data in an old root.
const CANDIDATES: &[(&str, &str, ImportKind, Option<&str>, bool)] = &[
    (
        ".openclaw",
        "openclaw-home",
        ImportKind::AssistantHome,
        Some("openclaw"),
        true,
    ),
    (
        ".clawdbot",
        "clawdbot-home",
        ImportKind::AssistantHome,
        Some("openclaw"),
        true,
    ),
    (
        ".moltbot",
        "moltbot-home",
        ImportKind::AssistantHome,
        Some("openclaw"),
        true,
    ),
    (
        ".hermes",
        "hermes-home",
        ImportKind::AssistantHome,
        Some("hermes"),
        true,
    ),
    (
        ".openhuman",
        "openhuman-home",
        ImportKind::AssistantHome,
        Some("openhuman"),
        true,
    ),
    (
        ".openhuman-staging",
        "openhuman-staging-home",
        ImportKind::AssistantHome,
        Some("openhuman"),
        true,
    ),
    (
        ".veronica",
        "veronica-home",
        ImportKind::AssistantHome,
        Some("veronica"),
        true,
    ),
];

/// Detection outcome: the generated manifest + the dry-run scan of every
/// detected source (row-count estimates ride along for free).
pub struct Detection {
    pub manifest: ImportManifest,
    pub scans: Vec<StoreScan>,
}

/// Scan `home` (the operator's home directory — parameterised for tests)
/// for complete prior-AI homes. Only paths that actually exist (and
/// match the expected file-vs-directory shape) make it into the manifest.
pub fn detect_sources(home: &Path) -> Detection {
    let mut sources = Vec::new();
    for (rel, name, kind, hint, want_dir) in CANDIDATES {
        let path: PathBuf = home.join(rel);
        let shape_ok = if *want_dir {
            path.is_dir()
        } else {
            path.is_file()
        };
        if !shape_ok {
            continue;
        }
        sources.push(ImportSource {
            name: (*name).to_string(),
            // Absolute path in the generated manifest — it must work no
            // matter where the operator saves/runs it from.
            path: path.to_string_lossy().into_owned(),
            kind: *kind,
            hint: hint.map(|h| h.to_string()),
        });
    }
    let manifest = ImportManifest {
        sources: sources.clone(),
    };
    // Reuse the dry-run scanners so the report carries real row-count
    // estimates instead of a bare file listing. `home` doubles as the
    // `--root` for `~/` expansion (paths here are absolute anyway).
    let scans = scan_all(&sources, home);
    Detection { manifest, scans }
}

/// Render the generated manifest as YAML with a review banner.
pub fn render_manifest_yaml(d: &Detection) -> anyhow::Result<String> {
    let body = serde_yaml::to_string(&d.manifest)?;
    Ok(format!(
        "# Generated by `neoth-migrate detect` — REVIEW BEFORE APPLY.\n\
         # Remove sources you don't want imported; add custom stores by\n\
         # hand (see examples/import-manifest.example.yaml). Then:\n\
         #   neoth-migrate dry-run --manifest <this file>\n\
         #   neoth-migrate apply   --manifest <this file> --confirm\n\
         {body}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fake_home() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        // OpenClaw layers dir with two markdown layers.
        let layers = home.join(".openclaw").join("layers");
        std::fs::create_dir_all(&layers).unwrap();
        std::fs::write(layers.join("layer_01.md"), "---\nfact one\n").unwrap();
        std::fs::write(layers.join("layer_02.md"), "---\nfact two\n").unwrap();
        // Hermes sqlite with the expected `memories` table.
        let hermes = home.join(".hermes").join("memory");
        std::fs::create_dir_all(&hermes).unwrap();
        let conn = rusqlite::Connection::open(hermes.join("hermes.db")).unwrap();
        conn.execute_batch(
            "CREATE TABLE memories (content TEXT, tags TEXT, importance REAL);\
             INSERT INTO memories VALUES ('remember x', 'a', 0.9);",
        )
        .unwrap();
        drop(conn);
        // Veronica JSONL.
        let veronica = home.join(".veronica");
        std::fs::create_dir_all(&veronica).unwrap();
        std::fs::write(
            veronica.join("memory.jsonl"),
            "{\"statement\":\"s\",\"scope\":\"global\",\"ts\":1}\n",
        )
        .unwrap();
        dir
    }

    #[test]
    fn detects_only_present_assistant_homes() {
        let home = fake_home();
        let d = detect_sources(home.path());
        let names: Vec<&str> = d.manifest.sources.iter().map(|s| s.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["openclaw-home", "hermes-home", "veronica-home"],
            "openhuman absent from the fake home must not be detected"
        );
        // Hints ride along for assistant-family provenance dispatch.
        let hermes = &d.manifest.sources[1];
        assert_eq!(hermes.hint.as_deref(), Some("hermes"));
        assert_eq!(hermes.kind, ImportKind::AssistantHome);
        // Paths are absolute (work from any cwd).
        assert!(Path::new(&d.manifest.sources[0].path).is_absolute());
        // Scans carry estimates for every detected source.
        assert_eq!(d.scans.len(), 3);
    }

    #[test]
    fn empty_home_detects_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let d = detect_sources(dir.path());
        assert!(d.manifest.sources.is_empty());
        assert!(d.scans.is_empty());
    }

    #[test]
    fn detects_current_nested_openhuman_home_as_one_complete_source() {
        let dir = tempfile::tempdir().unwrap();
        let workspace = dir
            .path()
            .join(".openhuman/users/operator/workspace/memory");
        std::fs::create_dir_all(&workspace).unwrap();
        std::fs::write(
            workspace.join("MEMORY.md"),
            "OpenHuman stores durable personal memory in nested workspaces.",
        )
        .unwrap();

        let detection = detect_sources(dir.path());
        assert_eq!(detection.manifest.sources.len(), 1);
        let source = &detection.manifest.sources[0];
        assert_eq!(source.name, "openhuman-home");
        assert_eq!(source.kind, ImportKind::AssistantHome);
        assert_eq!(source.hint.as_deref(), Some("openhuman"));
        assert_eq!(detection.scans[0].row_count, 1);
        assert!(matches!(
            detection.scans[0].status,
            crate::readers::ScanStatus::Ok
        ));
    }

    #[test]
    fn rendered_manifest_is_valid_yaml_with_review_banner() {
        let home = fake_home();
        let d = detect_sources(home.path());
        let yaml = render_manifest_yaml(&d).unwrap();
        assert!(yaml.starts_with("# Generated by `neoth-migrate detect`"));
        // Round-trips through the real manifest loader shape.
        let stripped: String = yaml
            .lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        let parsed: ImportManifest = serde_yaml::from_str(&stripped).unwrap();
        assert_eq!(parsed.sources.len(), 3);
    }

    #[test]
    fn wrong_shape_is_skipped() {
        // A FILE where the assistant-home DIRECTORY is expected must not detect.
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".openclaw"), "not a dir").unwrap();
        let d = detect_sources(dir.path());
        assert!(d.manifest.sources.is_empty());
    }
}
