//! GOLD-ADAPT-OH-01 — prior-AI source detector.
//!
//! Scans the CANONICAL install locations of the assistants NEOTH knows
//! how to import (OpenClaw, Hermes, OpenHuman, Veronica) and generates a
//! ready-to-edit `import-manifest.yaml` for `dry-run` / `apply`. Nothing
//! is imported here — detection is read-only and the operator reviews
//! the generated manifest before running `apply --confirm`.
//!
//! Canonical paths mirror `neothd::memory::foreign_import`'s module doc;
//! non-canonical stores (custom paths, memory-index JSON exports) are
//! declared by hand in the manifest as before — `detect` is a starter,
//! not a replacement for the manifest.

use std::path::{Path, PathBuf};

use crate::readers::{scan_all, ImportKind, ImportManifest, ImportSource, StoreScan};

/// One canonical candidate: (relative-to-home path, source name, kind,
/// sqlite/sub-format hint, expects-directory).
const CANDIDATES: &[(&str, &str, ImportKind, Option<&str>, bool)] = &[
    (
        ".openclaw/layers",
        "openclaw-layers",
        ImportKind::Markdown,
        None,
        true,
    ),
    (
        ".hermes/memory/hermes.db",
        "hermes-memory",
        ImportKind::Sqlite,
        Some("hermes"),
        false,
    ),
    (
        ".openhuman/db/profiles.sqlite",
        "openhuman-profiles",
        ImportKind::Sqlite,
        Some("openhuman"),
        false,
    ),
    (
        ".veronica/memory.jsonl",
        "veronica-memory",
        ImportKind::JsonFile,
        Some("veronica"),
        false,
    ),
];

/// Detection outcome: the generated manifest + the dry-run scan of every
/// detected source (row-count estimates ride along for free).
pub struct Detection {
    pub manifest: ImportManifest,
    pub scans: Vec<StoreScan>,
}

/// Scan `home` (the operator's home directory — parameterised for tests)
/// for canonical prior-AI stores. Only paths that actually exist (and
/// match the expected file-vs-directory shape) make it into the manifest.
pub fn detect_sources(home: &Path) -> Detection {
    let mut sources = Vec::new();
    for (rel, name, kind, hint, want_dir) in CANDIDATES {
        let path: PathBuf = home.join(rel);
        let shape_ok = if *want_dir {
            path.is_dir()
        } else {
            path.is_file()
        };
        if !shape_ok {
            continue;
        }
        sources.push(ImportSource {
            name: (*name).to_string(),
            // Absolute path in the generated manifest — it must work no
            // matter where the operator saves/runs it from.
            path: path.to_string_lossy().into_owned(),
            kind: *kind,
            hint: hint.map(|h| h.to_string()),
        });
    }
    let manifest = ImportManifest {
        sources: sources.clone(),
    };
    // Reuse the dry-run scanners so the report carries real row-count
    // estimates instead of a bare file listing. `home` doubles as the
    // `--root` for `~/` expansion (paths here are absolute anyway).
    let scans = scan_all(&sources, home);
    Detection { manifest, scans }
}

/// Render the generated manifest as YAML with a review banner.
pub fn render_manifest_yaml(d: &Detection) -> anyhow::Result<String> {
    let body = serde_yaml::to_string(&d.manifest)?;
    Ok(format!(
        "# Generated by `neoth-migrate detect` — REVIEW BEFORE APPLY.\n\
         # Remove sources you don't want imported; add custom stores by\n\
         # hand (see examples/import-manifest.example.yaml). Then:\n\
         #   neoth-migrate dry-run --manifest <this file>\n\
         #   neoth-migrate apply   --manifest <this file> --confirm\n\
         {body}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fake_home() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        // OpenClaw layers dir with two markdown layers.
        let layers = home.join(".openclaw").join("layers");
        std::fs::create_dir_all(&layers).unwrap();
        std::fs::write(layers.join("layer_01.md"), "---\nfact one\n").unwrap();
        std::fs::write(layers.join("layer_02.md"), "---\nfact two\n").unwrap();
        // Hermes sqlite with the expected `memories` table.
        let hermes = home.join(".hermes").join("memory");
        std::fs::create_dir_all(&hermes).unwrap();
        let conn = rusqlite::Connection::open(hermes.join("hermes.db")).unwrap();
        conn.execute_batch(
            "CREATE TABLE memories (content TEXT, tags TEXT, importance REAL);\
             INSERT INTO memories VALUES ('remember x', 'a', 0.9);",
        )
        .unwrap();
        drop(conn);
        // Veronica JSONL.
        let veronica = home.join(".veronica");
        std::fs::create_dir_all(&veronica).unwrap();
        std::fs::write(
            veronica.join("memory.jsonl"),
            "{\"statement\":\"s\",\"scope\":\"global\",\"ts\":1}\n",
        )
        .unwrap();
        dir
    }

    #[test]
    fn detects_only_present_canonical_sources() {
        let home = fake_home();
        let d = detect_sources(home.path());
        let names: Vec<&str> = d.manifest.sources.iter().map(|s| s.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["openclaw-layers", "hermes-memory", "veronica-memory"],
            "openhuman absent from the fake home must not be detected"
        );
        // Hints ride along for the sqlite sub-format dispatch.
        let hermes = &d.manifest.sources[1];
        assert_eq!(hermes.hint.as_deref(), Some("hermes"));
        assert_eq!(hermes.kind, ImportKind::Sqlite);
        // Paths are absolute (work from any cwd).
        assert!(Path::new(&d.manifest.sources[0].path).is_absolute());
        // Scans carry estimates for every detected source.
        assert_eq!(d.scans.len(), 3);
    }

    #[test]
    fn empty_home_detects_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let d = detect_sources(dir.path());
        assert!(d.manifest.sources.is_empty());
        assert!(d.scans.is_empty());
    }

    #[test]
    fn rendered_manifest_is_valid_yaml_with_review_banner() {
        let home = fake_home();
        let d = detect_sources(home.path());
        let yaml = render_manifest_yaml(&d).unwrap();
        assert!(yaml.starts_with("# Generated by `neoth-migrate detect`"));
        // Round-trips through the real manifest loader shape.
        let stripped: String = yaml
            .lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        let parsed: ImportManifest = serde_yaml::from_str(&stripped).unwrap();
        assert_eq!(parsed.sources.len(), 3);
    }

    #[test]
    fn wrong_shape_is_skipped() {
        // A FILE where the layers DIRECTORY is expected must not detect.
        let dir = tempfile::tempdir().unwrap();
        let oc = dir.path().join(".openclaw");
        std::fs::create_dir_all(&oc).unwrap();
        std::fs::write(oc.join("layers"), "not a dir").unwrap();
        let d = detect_sources(dir.path());
        assert!(d.manifest.sources.is_empty());
    }
}
