//! KF-04 — Idle-Time Skill Forge.
//!
//! When the dreaming pipeline composes a recurring-theme dream, the forge
//! synthesises a CANDIDATE skill YAML from it and stages it as an OB-03
//! [`ProposedAction`] (`kind = Skill`) for operator review. NEOTH never
//! writes the skill itself — the proposal lands in the proactive review
//! queue (`neoth proactive review` / `accept` / `reject`); only an
//! explicit operator accept adopts it. This is the "idle time turns
//! patterns into reusable skills" loop, gated behind a config flag.
//!
//! The forge is a pure adapter `Dream -> Option<ProposedAction>`: it
//! reuses the shipped skill builder ([`crate::skills::creator::build_manifest`])
//! so the `draft_yaml` is guaranteed loader-compatible, and the OB-03
//! queue ([`crate::proactive::action_staging`]) so the review/accept path
//! already exists (NOT primitive-ahead — the dreaming task is the live
//! producer, `neoth proactive` the live consumer). Unsuitable dreams
//! (no theme / no summary / un-slugifiable theme) yield `None`.

use crate::daemon::dreaming::Dream;
use crate::proactive::action_staging::{
    ProposalKind, ProposalStatus, ProposedAction, make_proposal_id, make_proposal_id_content_only,
};
use crate::skills::creator::{CreateParams, build_manifest};

// ── GAP-A: collector-signal → skill proposal ─────────────────────────────────

/// HERMES-06 GAP-A — forge a candidate skill proposal from a self-improvement
/// collector `PromptEdit` signal.
///
/// `topic` is the high-frequency episode topic that produced the signal
/// (e.g. `"kubernetes"`). `reason` is the human-readable rationale string
/// already generated by the collector tick. `ts_unix` is the collector tick
/// timestamp (seconds).
///
/// Returns `None` when `topic` can't be slugified into a valid skill id
/// (same guard as [`build_skill_proposal_from_dream`]).
///
/// Only call this for `PromptEdit` signals — `PatchSkill` and `Escalate`
/// require operator attention beyond what a skill draft can address.
pub fn build_proposal_from_collector_signal(
    topic: &str,
    reason: &str,
    ts_unix: i64,
) -> Option<ProposedAction> {
    let topic = topic.trim();
    let reason = reason.trim();
    if topic.is_empty() || reason.is_empty() {
        return None;
    }
    let id = slugify_theme(topic)?;
    let keywords = theme_keywords(topic);
    let system_prompt = format!(
        "When the operator's request touches the recurring topic \"{topic}\", apply this \
         context:\n\n{reason}\n\nBase your response on what NEOTH has actually observed \
         about the operator's use of this topic."
    );
    let params = CreateParams {
        id,
        description: format!(
            "Auto-forged from self-improvement collector signal for topic \"{topic}\""
        ),
        keywords,
        system_prompt,
    };
    let (_, yaml) = build_manifest(&params).ok()?;

    let title = format!("Skill: {topic}");
    let rationale = format!(
        "The self-improvement collector detected a high-frequency topic \"{topic}\" in your \
         recent episodes with no existing skill coverage. The suggestion: {reason}\n\n\
         Review the draft YAML below; `accept` adopts it into `~/.neoth/skills/`, \
         `reject` discards it. NEOTH never adds the skill on its own."
    );
    let proposal_id = make_proposal_id(ProposalKind::Skill, &title, &yaml, ts_unix);

    Some(ProposedAction {
        id: proposal_id,
        kind: ProposalKind::Skill,
        title,
        rationale,
        draft_yaml: yaml,
        generated_ts_unix: ts_unix,
        status: ProposalStatus::Pending,
        operator_note: String::new(),
    })
}

/// Slugify a dream theme label into a candidate skill id:
/// lowercase, non-alphanumeric runs collapse to a single `_`, trimmed,
/// `dream_`-prefixed, capped at 64 chars (the loader's id ceiling).
/// Returns `None` when the theme has no usable alphanumeric content.
fn slugify_theme(theme: &str) -> Option<String> {
    let mut slug = String::new();
    let mut prev_underscore = false;
    for ch in theme.trim().chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch.to_ascii_lowercase());
            prev_underscore = false;
        } else if !prev_underscore {
            slug.push('_');
            prev_underscore = true;
        }
    }
    let core = slug.trim_matches('_');
    if core.is_empty() {
        return None;
    }
    let id = format!("dream_{core}");
    // Cap at the loader's 64-char id limit (validate_skill_id enforces it
    // too, but truncate cleanly so we never hand build_manifest a value
    // it will reject for length alone).
    let id: String = id.chars().take(64).collect();
    Some(id.trim_matches('_').to_string()).filter(|s| !s.is_empty())
}

/// Extract trigger keywords from a theme label: lowercase alphanumeric
/// tokens of length >= 3, de-duplicated, order-preserving, capped at 8.
fn theme_keywords(theme: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for tok in theme
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|t| t.len() >= 3)
    {
        let lower = tok.to_ascii_lowercase();
        if !out.contains(&lower) {
            out.push(lower);
        }
        if out.len() >= 8 {
            break;
        }
    }
    out
}

/// GOLD-ADAPT-KB-03 — forge an operator-reviewed skill draft from a tool-call
/// sequence that passed the independent-session confidence gate.
pub fn build_proposal_from_distill_pattern(
    sequence: &[String],
    occurrences: usize,
    supporting_sessions: usize,
    eligible_sessions: usize,
    confidence: f64,
    ts_unix: i64,
) -> Option<ProposedAction> {
    if sequence.len() < 2
        || supporting_sessions < 4
        || eligible_sessions < supporting_sessions
        || !confidence.is_finite()
        || confidence <= 0.8
        || confidence > 1.0
    {
        return None;
    }
    let sequence_label = sequence.join(" -> ");
    let slug = slugify_theme(&sequence_label)?;
    let core = slug.strip_prefix("dream_").unwrap_or(&slug);
    let id: String = format!("distill_{core}").chars().take(64).collect();
    let steps = sequence
        .iter()
        .enumerate()
        .map(|(index, tool)| format!("{}. Invoke `{tool}` and verify its result.", index + 1))
        .collect::<Vec<_>>()
        .join("\n");
    let params = CreateParams {
        id,
        description: format!(
            "Candidate workflow distilled from repeated tool sequence: {sequence_label}"
        ),
        keywords: theme_keywords(&sequence_label),
        system_prompt: format!(
            "When the operator's task matches this recurring workflow, use the observed tool-call \
             order below. Validate prerequisites before the first call, preserve each call's output \
             for the next step, and stop with the concrete error if a step fails. Never claim a step \
             completed unless its tool result confirms it.\n\n{steps}"
        ),
    };
    let (_, draft_yaml) = build_manifest(&params).ok()?;
    let title = format!("Skill: {sequence_label}");
    let proposal_id = make_proposal_id_content_only(ProposalKind::Skill, &title, &draft_yaml);
    let rationale = format!(
        "The nightly self-improvement pass observed this exact tool workflow {occurrences} times \
         across {supporting_sessions}/{eligible_sessions} independent session traces \
         ({:.1}% confidence). The draft remains pending until explicit operator approval; NEOTH \
         never activates it automatically.",
        confidence * 100.0
    );

    Some(ProposedAction {
        id: proposal_id,
        kind: ProposalKind::Skill,
        title,
        rationale,
        draft_yaml,
        generated_ts_unix: ts_unix,
        status: ProposalStatus::Pending,
        operator_note: String::new(),
    })
}

/// KF-04 — forge a candidate skill proposal from one dream. Pure;
/// `None` when the dream can't yield a sensible skill (empty theme,
/// empty summary, un-slugifiable theme, or the builder rejects the id).
pub fn build_skill_proposal_from_dream(dream: &Dream) -> Option<ProposedAction> {
    let theme = dream.theme_label.trim();
    let summary = dream.summary.trim();
    if theme.is_empty() || summary.is_empty() {
        return None;
    }
    let id = slugify_theme(theme)?;
    let keywords = theme_keywords(theme);
    let system_prompt = format!(
        "When the operator's request touches the recurring theme \"{theme}\", bring this \
         context to bear:\n{summary}\n\nBe concrete and stay grounded in what NEOTH has \
         actually observed about this theme."
    );
    let params = CreateParams {
        id,
        description: format!("Auto-forged from the \"{theme}\" dream ({})", dream.day),
        keywords,
        system_prompt,
    };
    // build_manifest validates the id (charset/length) + round-trips the
    // YAML through serde so the draft is loader-compatible. A rejected id
    // (or any builder error) means this dream can't forge a skill -> None.
    let (_, yaml) = build_manifest(&params).ok()?;

    let title = format!("Skill: {theme}");
    let rationale = format!(
        "NEOTH noticed a recurring theme \"{theme}\" on {} (across {} source event(s)) and \
         drafted a reusable skill from it. Review the YAML below; `accept` adopts it into \
         `~/.neoth/skills/`, `reject` discards it. NEOTH never adds the skill on its own.\n\n\
         Dream summary:\n{summary}",
        dream.day,
        dream.event_ids.len(),
    );
    let ts = dream.composed_ts_unix;
    let proposal_id = make_proposal_id(ProposalKind::Skill, &title, &yaml, ts);

    Some(ProposedAction {
        id: proposal_id,
        kind: ProposalKind::Skill,
        title,
        rationale,
        draft_yaml: yaml,
        generated_ts_unix: ts,
        status: ProposalStatus::Pending,
        operator_note: String::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::daemon::dreaming::compose_dream;

    fn dream_with(theme: &str, summary: &str) -> Dream {
        // compose_dream builds a deterministic Dream; override the two
        // fields the forge reads so the test is explicit.
        let mut d = compose_dream("2026-06-02", theme, &[]);
        d.theme_label = theme.to_string();
        d.summary = summary.to_string();
        d.composed_ts_unix = 1_700_000_000;
        d
    }

    #[test]
    fn forges_a_skill_from_a_normal_dream() {
        let d = dream_with(
            "WiFi troubleshooting",
            "Operator repeatedly debugs router drops.",
        );
        let p = build_skill_proposal_from_dream(&d).expect("normal dream forges a skill");
        assert_eq!(p.kind, ProposalKind::Skill);
        assert!(p.title.contains("WiFi troubleshooting"));
        // The draft YAML is a real, loader-shaped skill manifest.
        assert!(p.draft_yaml.contains("id:"));
        assert!(p.draft_yaml.contains("dream_wifi_troubleshooting"));
        assert!(p.draft_yaml.contains("system_prompt:"));
        // Rationale carries the operator-facing why + the summary.
        assert!(p.rationale.contains("recurring theme"));
        assert!(p.rationale.contains("router drops"));
        assert!(matches!(p.status, ProposalStatus::Pending));
    }

    #[test]
    fn empty_theme_or_summary_forges_nothing() {
        assert!(build_skill_proposal_from_dream(&dream_with("", "has summary")).is_none());
        assert!(build_skill_proposal_from_dream(&dream_with("has theme", "")).is_none());
        assert!(build_skill_proposal_from_dream(&dream_with("   ", "  ")).is_none());
    }

    #[test]
    fn un_slugifiable_theme_forges_nothing() {
        // A theme with no alphanumerics can't become a valid skill id.
        assert!(build_skill_proposal_from_dream(&dream_with("!!! ??? ...", "summary")).is_none());
    }

    #[test]
    fn slugify_collapses_and_prefixes() {
        assert_eq!(
            slugify_theme("WiFi  drops!!").as_deref(),
            Some("dream_wifi_drops")
        );
        assert_eq!(
            slugify_theme("café-notes").as_deref(),
            Some("dream_caf_notes")
        );
        assert_eq!(slugify_theme("   "), None);
        assert_eq!(slugify_theme("###"), None);
    }

    #[test]
    fn keywords_dedupe_drop_short_and_cap() {
        let kw = theme_keywords("the WiFi wifi router AND the AP setup x y z");
        assert!(kw.contains(&"wifi".to_string()));
        assert!(kw.contains(&"router".to_string()));
        assert!(kw.contains(&"the".to_string())); // len 3 kept
        assert!(!kw.contains(&"x".to_string())); // len 1 dropped
        // "wifi" appears twice in input -> once in output.
        assert_eq!(kw.iter().filter(|k| *k == "wifi").count(), 1);
        assert!(kw.len() <= 8);
    }

    #[test]
    fn proposal_id_is_deterministic_for_same_dream() {
        let d = dream_with("topic", "summary text");
        let a = build_skill_proposal_from_dream(&d).unwrap();
        let b = build_skill_proposal_from_dream(&d).unwrap();
        assert_eq!(
            a.id, b.id,
            "same dream -> same proposal id (idempotent staging)"
        );
    }

    // ── GAP-A: build_proposal_from_collector_signal ───────────────────────────

    #[test]
    fn collector_signal_forges_a_skill_proposal() {
        let p = build_proposal_from_collector_signal(
            "kubernetes",
            "frequent topic 'kubernetes' (12 episodes in window) with no existing skill coverage",
            1_700_000_100,
        )
        .expect("normal signal yields a proposal");
        assert_eq!(p.kind, ProposalKind::Skill);
        assert!(p.title.contains("kubernetes"), "title carries the topic");
        assert!(p.draft_yaml.contains("dream_kubernetes"), "slug in yaml");
        assert!(p.draft_yaml.contains("id:"), "yaml has id field");
        assert!(
            p.rationale.contains("self-improvement collector"),
            "rationale mentions source"
        );
        assert!(
            p.rationale.contains("kubernetes"),
            "rationale carries the topic"
        );
        assert!(matches!(p.status, ProposalStatus::Pending));
    }

    #[test]
    fn collector_signal_empty_topic_or_reason_yields_none() {
        assert!(build_proposal_from_collector_signal("", "some reason", 1_700_000_100).is_none());
        assert!(build_proposal_from_collector_signal("topic", "", 1_700_000_100).is_none());
        assert!(build_proposal_from_collector_signal("   ", "  ", 1_700_000_100).is_none());
    }

    #[test]
    fn collector_signal_proposal_id_deterministic() {
        let a =
            build_proposal_from_collector_signal("docker", "reason text", 1_700_000_200).unwrap();
        let b =
            build_proposal_from_collector_signal("docker", "reason text", 1_700_000_200).unwrap();
        assert_eq!(a.id, b.id, "same inputs -> same proposal id");
    }

    #[test]
    fn collector_signal_un_slugifiable_yields_none() {
        assert!(build_proposal_from_collector_signal("!!! ???", "reason", 1_700_000_300).is_none());
    }

    #[test]
    fn distill_pattern_forges_loader_compatible_pending_skill() {
        let sequence = vec!["filesystem/read".to_string(), "editor/apply".to_string()];
        let proposal =
            build_proposal_from_distill_pattern(&sequence, 6, 5, 6, 5.0 / 6.0, 1_700_000_400)
                .expect("high-confidence repeated sequence must forge a proposal");
        assert_eq!(proposal.kind, ProposalKind::Skill);
        assert!(matches!(proposal.status, ProposalStatus::Pending));
        assert!(
            proposal
                .draft_yaml
                .contains("distill_filesystem_read_editor_apply")
        );
        assert!(proposal.draft_yaml.contains("filesystem/read"));
        assert!(proposal.rationale.contains("5/6"));

        let duplicate =
            build_proposal_from_distill_pattern(&sequence, 6, 5, 6, 5.0 / 6.0, 1_800_000_000)
                .unwrap();
        assert_eq!(proposal.id, duplicate.id, "proposal dedup is content-bound");
    }

    #[test]
    fn distill_pattern_rejects_weak_or_non_independent_evidence() {
        let sequence = vec!["read".to_string(), "edit".to_string()];
        assert!(
            build_proposal_from_distill_pattern(&sequence, 20, 1, 1, 1.0, 1).is_none(),
            "one looping session is not independent evidence"
        );
        assert!(
            build_proposal_from_distill_pattern(&sequence, 4, 4, 5, 0.8, 1).is_none(),
            "confidence must be strictly greater than 0.8"
        );
    }
}
